import Link from "next/link";
import { ArrowRight, Check } from "lucide-react";
import { Brand } from "@/components/brand";

const plans = [
  { name: "Observe", price: "$0", note: "For evaluating one critical journey", features: ["3 runs each month", "All five personas", "Evidence-backed reports", "7-day history"] },
  { name: "Practice", price: "$89", note: "For product teams shipping every week", features: ["60 runs each month", "Deployment webhooks", "90-day trends", "Shared reports", "Priority run queue"], featured: true },
  { name: "Protect", price: "Custom", note: "For multiple products and regulated teams", features: ["Custom run volume", "Private browser worker", "SSO and role controls", "Extended evidence retention", "Security review"] }
];

export default function PricingPage() { return <main className="simple-marketing"><nav className="nav-wrap"><Brand /><div className="nav-links"><Link href="/#how">How it works</Link><Link href="/pricing">Pricing</Link><Link href="/docs">Docs</Link></div><Link className="button dark" href="/dashboard">Open demo <ArrowRight size={15} /></Link></nav><section className="simple-hero"><span className="kicker"><i /> Clear limits, no invented proof</span><h1>Pay for the journeys<br />you need to protect.</h1><p>Start with a real flow. Move up when continuous coverage becomes part of your release process.</p></section><section className="pricing-grid section-wrap">{plans.map(plan=><article className={plan.featured?"featured":""} key={plan.name}>{plan.featured&&<span className="popular">Most useful</span>}<h2>{plan.name}</h2><p>{plan.note}</p><strong>{plan.price}<small>{plan.price.startsWith("$")&&plan.price!=="$0"?" / month":""}</small></strong><Link className={`button ${plan.featured?"primary":"dark"}`} href="/dashboard">{plan.price==="Custom"?"Talk to us":"Start with this plan"}</Link><ul>{plan.features.map(feature=><li key={feature}><Check size={15}/>{feature}</li>)}</ul></article>)}</section><section className="pricing-note section-wrap"><h2>Important deployment boundary</h2><p>The web application runs on Vercel. Long-lived Playwright sessions require a dedicated browser worker for production use; the public demo proves the model decision, deterministic action validation, wallet verification, and devnet receipt paths without misrepresenting a simulated browser as a live one.</p></section></main>; }
