import Link from "next/link";
import { ArrowRight, Check, Eye, FileSearch, Gauge, LockKeyhole, Play, RefreshCw, Route, ShieldCheck } from "lucide-react";
import { Brand } from "@/components/brand";
import { PersonaGrid } from "@/components/persona-grid";
import { RunPreview } from "@/components/run-preview";
import { HeroMotion, MotionReveal } from "@/components/marketing-motion";

const features = [
  { icon: Eye, title: "Real browser behavior", text: "Each persona reads, clicks, types, waits, and changes course inside the same live flow your customers use." },
  { icon: FileSearch, title: "Evidence, not opinions", text: "Every finding points back to the exact step, page state, action, and in-character reasoning that produced it." },
  { icon: ShieldCheck, title: "Hard safety boundary", text: "A deterministic check blocks payment completion and sensitive personal data before any browser action executes." },
  { icon: RefreshCw, title: "Continuous retesting", text: "Trigger a fresh run from your deployment pipeline or keep a recurring watch on critical journeys." },
  { icon: Gauge, title: "Friction trends", text: "Track severity, pass rate, and regressions by flow and customer profile instead of comparing disconnected reports." },
  { icon: Route, title: "One shared record", text: "Send a focused report to product, design, support, and engineering with the evidence already attached." }
];

export default function HomePage() {
  return (
    <main className="marketing">
      <nav className="nav-wrap"><Brand /><div className="nav-links"><Link href="#how">How it works</Link><Link href="#personas">Personas</Link><Link href="/pricing">Pricing</Link><Link href="/proof">Proof</Link><Link href="/docs">Docs</Link></div><div className="nav-actions"><Link className="button ghost" href="/sign-in">Sign in</Link><Link className="button dark" href="/dashboard">Open demo <ArrowRight size={15} /></Link></div></nav>
      <section className="hero section-wrap">
        <div className="hero-copy"><span className="kicker"><i /> Autonomous customer testing</span><h1>Watch customers struggle <em>before</em> they leave.</h1><p>MirrorQA sends distinct synthetic customers through your real product. See exactly where each one hesitates, gets confused, or gives up—with the evidence attached.</p><div className="hero-actions"><Link className="button primary large" href="/dashboard">Explore the live demo <ArrowRight size={17} /></Link><Link className="watch-link" href="#how"><span><Play size={14} fill="currentColor" /></span> See the 90-second tour</Link></div><div className="hero-note"><ShieldCheck size={16} /><span>No card required. Payment and personal-data actions are blocked in code.</span></div></div>
        <HeroMotion><div className="visual-glow" /><RunPreview /><div className="floating finding-chip"><span>High friction</span><b>Pricing uncertainty</b><small>Evidence at step 02</small></div><div className="floating safe-chip"><LockKeyhole size={15} /><span><b>Action blocked</b><small>Payment completion</small></span></div></HeroMotion>
      </section>
      <section className="signal-strip"><div className="section-wrap"><span>Built for teams protecting</span><div><b>Signup</b><i /> <b>Checkout</b><i /> <b>Onboarding</b><i /> <b>Support</b></div><span>from silent abandonment</span></div></section>
      <MotionReveal className="section-wrap intro" ><section id="how"><span className="section-index">01 / The mechanism</span><div className="section-heading"><h2>Your QA checks whether it works.<br />MirrorQA checks whether people can use it.</h2><p>A working button can still be hard to find. A valid form can still feel unsafe. The only way to discover those failures is to move through the journey with a customer’s priorities and constraints.</p></div><div className="mechanism-grid"><article><span>01</span><h3>Define a journey</h3><p>Give MirrorQA a starting URL, the outcome a customer should reach, and the profiles you need to understand.</p></article><article><span>02</span><h3>Watch the attempt</h3><p>An isolated browser session observes the current page, chooses one action, executes it, then reassesses.</p></article><article><span>03</span><h3>Act on proof</h3><p>Review specific friction with its screenshot, reasoning, severity, and the exact step that triggered it.</p></article></div></section></MotionReveal>
      <section className="dark-section" id="personas"><div className="section-wrap"><span className="section-index light">02 / Customer profiles</span><div className="section-heading light"><h2>Five customers.<br />Five ways to lose them.</h2><p>Not a tone change pasted over one generic agent. Each profile follows a different decision policy, attention pattern, and threshold for abandonment.</p></div><PersonaGrid /></div></section>
      <section className="section-wrap feature-section"><span className="section-index">03 / What you get</span><div className="section-heading"><h2>A clear account of<br />what happened and why.</h2><p>MirrorQA joins live interaction evidence with customer-specific reasoning, then keeps the result useful beyond a single run.</p></div><div className="feature-grid">{features.map(({ icon: Icon, title, text }) => <article key={title}><span className="feature-icon"><Icon size={20} /></span><h3>{title}</h3><p>{text}</p></article>)}</div></section>
      <section className="safety section-wrap"><div className="safety-copy"><span className="section-index">04 / Safety boundary</span><h2>The model proposes.<br />Code decides.</h2><p>No language model gets the final word on a risky action. Every click and input passes through a deterministic policy before it reaches the browser.</p><ul><li><Check size={16} /> Blocks purchase and payment completion controls</li><li><Check size={16} /> Rejects sensitive identity and financial data</li><li><Check size={16} /> Records every blocked action in the evidence trail</li></ul><Link className="text-link" href="/docs#safety">Read the safety architecture <b>→</b></Link></div><div className="code-card"><div className="code-top"><span>Safety check</span><span className="verified"><i /> Verified before execution</span></div><pre><code><span className="muted">// Proposed browser action</span>{`\n`}<span className="blue">action</span> = &#123;{`\n`}  kind: <span className="green">&quot;click&quot;</span>,{`\n`}  label: <span className="green">&quot;Confirm subscription&quot;</span>{`\n`}&#125;{`\n\n`}<span className="blue">validate</span>(action){`\n`}  → <span className="red">BLOCKED</span>{`\n`}  → PAYMENT_COMPLETION{`\n`}</code></pre><div className="code-result"><LockKeyhole size={17} /><span><b>Browser action not executed</b><small>Block event added to run trace</small></span></div></div></section>
      <section className="cta"><div className="section-wrap"><span className="kicker pale">See through their eyes</span><h2>Find the friction your<br />happy path never sees.</h2><p>Run a real customer journey with five perspectives your internal team cannot reliably simulate.</p><Link className="button cream large" href="/dashboard">Explore MirrorQA <ArrowRight size={17} /></Link></div></section>
      <footer><div className="section-wrap footer-main"><div><Brand inverse /><p>Customer perspective, captured before it becomes churn.</p></div><div><b>Product</b><Link href="#how">How it works</Link><Link href="/pricing">Pricing</Link><Link href="/dashboard">Demo</Link></div><div><b>Company</b><Link href="/proof">Live proof lab</Link><Link href="/docs">Documentation</Link></div><div><b>Legal</b><Link href="/privacy">Privacy</Link><Link href="/terms">Terms</Link></div></div><div className="section-wrap footer-bottom"><span>© 2026 MirrorQA. Built with restraint.</span><span><i /> Systems operational</span></div></footer>
    </main>
  );
}
